/* Les synthèses, écrites à la main après lecture de chaque sommaire.
   Rien n'y figure qui ne soit dans les arrêts cités : chaque affirmation porte
   le numéro de pourvoi qui la fonde. */
module.exports = {
A: [
 "Le contentieux de la mise en place s'est concentré sur une seule question : le découpage de l'entreprise en établissements distincts. La Cour y a fixé trois choses. D'abord la compétence : les contestations de la décision administrative fixant le nombre et le périmètre des établissements relèvent du tribunal — d'instance hier, judiciaire aujourd'hui — statuant en dernier ressort, à l'exclusion de tout autre recours (n° 18-23.655 ; QPC n° 20-40.001, non-lieu à renvoi). Ensuite l'office du juge : saisi de cette contestation, il se prononce sur la légalité de la décision au regard de l'ensemble des circonstances de fait à la date où elle a été prise (n° 19-11.918), et lorsqu'il l'annule il lui appartient de statuer lui-même sur le découpage (n° 19-21.086). Enfin le point de départ du délai : la notification de la décision de l'employeur consiste en une information spécifique et préalable à l'organisation des élections (n° 18-22.948).",
 "Sur le critère de fond, la Cour a repris la main à plusieurs reprises. L'article L. 2313-4 ne retient que l'autonomie de gestion du responsable d'établissement, notamment en matière de gestion du personnel. Les juges du fond qui ajoutaient à ce texte ont été censurés : la centralisation des fonctions support et l'existence de procédures de gestion définies au siège n'excluent pas l'autonomie (n° 19-17.298) ; trois cassations successives rappellent que le texte se suffit à lui-même (n° 19-12.011, n° 19-23.153, n° 19-23.745). L'ordre des sources est strict : accord majoritaire d'abord, décision unilatérale de l'employeur ensuite, décision administrative en dernier lieu (n° 20-60.258) ; un accord conclu après réouverture des négociations rend caduque la décision administrative antérieure (n° 19-21.057).",
 "Le passage de l'ancien au nouveau droit a produit sa propre série. L'article 9, VII, de l'ordonnance du 22 septembre 2017 met fin, à la date du premier tour, aux stipulations conventionnelles relatives aux délégués du personnel, au comité d'entreprise et au CHSCT (n° 18-18.401, n° 19-24.400) ; l'article 9, III, proroge les mandats en cours pour assurer la mise en place du comité (n° 19-14.021). Cette série est datée : elle a épuisé son objet, mais elle reste utile pour les litiges portant sur des accords antérieurs à 2018 encore appliqués.",
 "Deux apports plus récents méritent d'être retenus. Les représentants de proximité ne peuvent être mis en place que par l'accord d'entreprise majoritaire visé à L. 2313-7, qui en fixe lui-même le nombre, les attributions et les modalités de désignation : aucune autre voie n'est ouverte (n° 22-13.303) ; le contentieux de leur désignation suit celui des membres du comité (n° 21-13.206). Et l'accord collectif reconnaissant une unité économique et sociale, dont l'objet est de mettre en place un comité selon le droit commun, n'est ni un accord interentreprises ni un accord de groupe (n° 22-13.672) : sa contestation obéit au régime de l'accord d'entreprise.",
],
B1: [
 "La Cour a fermé le protocole préélectoral. Lorsqu'il est conclu aux conditions de double majorité de l'article L. 2314-6, il ne peut plus être contesté devant le juge judiciaire qu'en ce qu'il contiendrait des stipulations contraires à l'ordre public, notamment aux principes généraux du droit électoral (n° 20-20.962, confirmé n° 23-15.822). C'est la règle la plus utile en pratique : un protocole régulièrement signé purge les irrégularités qu'il couvre.",
 "Cette fermeture a un prix pour l'employeur : la loyauté de la négociation. Il doit mettre à la disposition des organisations participantes les éléments d'information indispensables (n° 19-10.780). Elle a un prix aussi pour les syndicats : celui qui a signé sans réserve et présenté des candidats n'est plus recevable à invoquer par voie d'exception, après le scrutin, une proportion de femmes et d'hommes différente de celle du protocole (n° 18-20.841) ; le syndicat affilié à une fédération signataire ne peut davantage en contester la validité (n° 22-13.535).",
 "Le reste de la série tient à la procédure. L'invitation à négocier doit atteindre les organisations qui remplissent les conditions de l'article L. 2314-5 (n° 17-26.522), et la contestation de l'existence d'une section syndicale peut se greffer sur ce litige, à charge pour le syndicat de justifier de deux adhérents à la date de la désignation (n° 20-16.696). La saisine de l'autorité administrative aux fins de répartition suspend le processus électoral jusqu'à sa décision (n° 20-60.262) ; à défaut d'accord valable et en l'absence de saisine du tribunal, c'est à l'employeur de fixer les modalités d'organisation du vote (n° 21-11.737). Le juge de l'élection, enfin, dispose du pouvoir de prendre toutes mesures nécessaires au bon déroulement des opérations (n° 17-27.442).",
],
B2: [
 "L'électorat et l'éligibilité se sont joués sur l'article L. 2314-19 et sur l'exclusion des salariés assimilés à l'employeur. Deux conditions alternatives, et strictement entendues : disposer d'une délégation écrite particulière d'autorité, ou représenter effectivement l'employeur devant le comité. Le responsable du service de sécurité qui n'intervient que ponctuellement, avec voix seulement consultative, n'entre dans aucune des deux (n° 19-25.982) ; le gérant d'une société de l'unité économique et sociale, fût-il titulaire d'un contrat de travail conclu avec une autre société du même ensemble, y entre (n° 24-16.430).",
 "Cette exclusion a été contestée devant le Conseil constitutionnel : la question a été renvoyée en 2021 (n° 21-40.013), et le législateur est intervenu par la loi du 21 décembre 2022, dont la Cour fait application depuis (n° 25-14.195). C'est le point de la rubrique où l'état du droit a le plus bougé : les décisions antérieures à 2023 doivent être relues à la lumière du texte nouveau.",
 "Sur les salariés mis à disposition, la règle est stable : présents dans les locaux de l'entreprise utilisatrice et y travaillant depuis au moins un an, ils doivent être inscrits sur ses listes électorales (n° 22-10.903), et le droit d'option exercé sous l'empire d'un texte abrogé ne peut leur être opposé (n° 18-60.149).",
],
B3: [
 "La répartition du personnel dans les collèges et celle des sièges entre catégories obéissent au même schéma que le découpage en établissements : accord aux conditions de l'article L. 2314-6, à défaut décision administrative, contestation devant le tribunal judiciaire en dernier ressort à l'exclusion de tout autre recours (n° 21-19.551, n° 23-24.013). La décision administrative doit être motivée, au sens du code des relations entre le public et l'administration (n° 25-14.504) ; pour la prendre, l'autorité applique un critère de proportionnalité entre l'effectif de chaque collège et le nombre de sièges, tempéré par les circonstances particulières de l'entreprise (n° 17-27.175).",
 "L'effet de la saisine est acquis : les mandats des élus en cours sont prorogés de plein droit jusqu'à la proclamation des résultats (n° 22-22.524), et le texte s'applique même lorsque ces mandats sont encore en cours (n° 19-12.896). Deux règles complètent la série : les syndicats affiliés à une même confédération ne peuvent présenter qu'une seule liste par collège (n° 16-22.168), et le suppléant remplaçant un titulaire doit être élu sur une liste présentée par la même organisation syndicale (n° 21-11.347).",
],
B4: [
 "C'est la série la plus fournie du recueil, et la plus technique. La règle est double : la liste doit comporter un nombre de femmes et d'hommes correspondant à leur part dans le collège, et les candidats doivent y alterner jusqu'à épuisement des candidats d'un sexe. À chaque branche correspond une sanction distincte. La méconnaissance de la proportion entraîne l'annulation de l'élection des derniers élus du sexe surreprésenté, en suivant l'ordre inverse de la liste (n° 18-60.173) ; la méconnaissance de l'alternance entraîne l'annulation de l'élection de tout élu dont le positionnement est irrégulier (n° 17-60.263, n° 19-12.596).",
 "Trois arrêts du même jour ont posé l'obligation de présenter au moins un candidat du sexe minoritaire lorsque plusieurs sièges sont à pourvoir (n° 18-23.513, n° 19-10.826, n° 19-10.855). La proportion se lit dans le protocole, arrêtée selon les effectifs connus lors de la négociation, et à défaut fixée par l'employeur (n° 20-60.118). Le texte est d'ordre public absolu (n° 24-11.781), et l'alternance s'examine candidat par candidat : hors le cas du dernier alinéa de l'article L. 2314-30, elle n'impose pas que le premier de la liste soit du sexe majoritaire (n° 24-16.515). Les élections partielles suivent les mêmes règles (n° 21-60.183).",
 "Le contentieux des effets est aussi net. L'annulation peut être demandée avant l'élection, le juge statuant alors en reportant s'il le faut le scrutin (n° 18-26.568). Après l'élection, elle ne fait perdre son mandat à l'élu qu'à compter du jour où elle est prononcée et reste sans incidence sur sa candidature et son score (n° 19-15.505). Surtout, le siège annulé ne se remplace pas : ni par la rectification de l'attribution des sièges (n° 23-60.107), ni par un suppléant au titre de l'article L. 2314-37 (n° 20-16.859, n° 24-60.159). La sanction est donc réellement une perte de représentation, non un simple remplacement.",
 "Le dispositif a été soumis quatre fois au Conseil constitutionnel depuis 2019 sans renvoi (n° 19-18.900, n° 21-11.813, n° 23-40.014, n° 23-17.506), après un renvoi en 2018 portant sur l'ancien droit (n° 18-11.720). La constitutionnalité de l'ensemble peut être tenue pour acquise.",
],
B5: [
 "Trois arrêts seulement, mais qui suffisent à cadrer le vote électronique. Il peut être ouvert par accord d'entreprise ou de groupe et, à défaut d'accord, par décision unilatérale de l'employeur (n° 19-23.533). Le code électoral ne lui est pas applicable : le test du système et la vérification que l'urne est vide, scellée et chiffrée n'ont pas à intervenir immédiatement avant l'ouverture du scrutin (n° 20-17.076). La liste d'émargement n'est accessible qu'aux membres du bureau de vote, à fins de contrôle, et il appartient aux parties intéressées d'en demander la communication après la clôture (n° 22-21.249).",
],
B6: [
 "Le délai de quinze jours de l'article R. 2314-24 gouverne l'ensemble du contentieux électoral. La Cour en a précisé le champ : la contestation des résultats qui procède d'une contestation du périmètre — lequel n'est pas un élément spécifique au premier tour — reste recevable dans les quinze jours du second (n° 20-17.286). Les conditions de validité de la désignation d'un représentant syndical s'apprécient à la date de la désignation (n° 24-11.467), tandis que le droit du syndicat de désigner s'apprécie à la date des dernières élections (n° 22-11.461).",
 "Deux décisions de 2026 méritent d'être signalées : le journaliste rémunéré à la pige n'échappe pas aux articles L. 2314-2 et L. 2314-19 (n° 24-16.560), et le syndicat désaffilié de la confédération sous le sigle de laquelle il avait présenté des candidats n'est plus recevable à contester les désignations opérées par cette confédération (n° 22-16.020).",
],
C: [
 "L'apport majeur de la période tient en deux arrêts du 2 mars 2022 : le comité social et économique est recevable à invoquer, par voie d'exception et sans condition de délai, l'illégalité d'une clause d'un accord collectif qui viole ses droits propres (n° 20-20.077, n° 20-16.002). La Cour l'a fondé sur le droit au recours juridictionnel effectif — article 16 de la Déclaration de 1789, article 47 de la Charte, article 6 de la Convention européenne — et sur la directive 2002/14. Le délai de deux mois de l'article L. 2262-14 ne lui est donc pas opposable par voie d'exception. C'est l'arme contentieuse la plus efficace dont dispose aujourd'hui un comité contre un accord qui l'a dépouillé d'une prérogative.",
 "Le second acquis est la sanction du défaut de consultation : lorsqu'elle est légalement obligatoire, son absence constitue un trouble manifestement illicite (n° 23-13.806), ce qui ouvre le référé. Corrélativement, la Cour refuse d'enchaîner les consultations : la consultation ponctuelle sur une modification de l'organisation économique ou juridique, ou sur une restructuration, n'est pas subordonnée à la consultation préalable sur les orientations stratégiques (n° 20-23.660).",
 "Le reste tient à la répartition des compétences et à la procédure. Le droit d'alerte économique de l'article L. 2312-63 appartient au comité central, non aux comités d'établissement, parce qu'il suppose une situation affectant l'entreprise (n° 21-13.312) ; le comité d'établissement a les mêmes attributions que celui d'entreprise, mais dans la limite des pouvoirs du chef d'établissement (n° 21-11.935). Devant le président du tribunal judiciaire statuant selon la procédure accélérée au fond, la date de saisine est celle de l'assignation, non celle du placement (n° 23-11.339) : l'erreur est fréquente et coûte le délai.",
 "Trois décisions plus isolées complètent la rubrique : l'ouverture des activités sociales et culturelles à l'ensemble des salariés et des stagiaires, que le comité ne peut restreindre (n° 22-16.812) ; le pouvoir du membre de la délégation du personnel de saisir le juge des atteintes aux droits des personnes en vertu de l'article L. 2312-59 (n° 24-15.990) ; et la qualification d'acte administratif faisant grief de la lettre par laquelle l'administration indique que le plan de sauvegarde de l'emploi dont elle est saisie n'est pas l'outil adéquat, ce qui prive le juge judiciaire de compétence (n° 21-14.304).",
],
D: [
 "Six arrêts seulement, mais qui couvrent l'essentiel du régime. À défaut d'accord conclu dans les conditions de l'article L. 2312-19, les trois consultations récurrentes sont annuelles et leur contenu est celui que fixe le code (n° 21-25.233, n° 21-25.748) : l'accord est la seule voie pour en modifier la périodicité, le contenu ou le niveau. Un accord peut fixer le niveau auquel elles sont conduites, y compris au seul niveau central (n° 23-10.857).",
 "Sur la base de données économiques, sociales et environnementales, la Cour a jugé que les demandes relatives à l'accès et aux informations qu'elle contient relèvent du régime de l'article L. 2312-59 (n° 24-10.326) : le membre du comité dispose donc d'une voie directe. La mission de l'expert désigné pour la consultation sur la politique sociale comprend l'analyse de l'évolution des rémunérations dans toutes leurs composantes et celle de la politique de recrutement et des modalités de départ, notamment les ruptures conventionnelles et les licenciements pour inaptitude (n° 20-17.186).",
],
E: [
 "Les heures de délégation forment l'essentiel de la série. Le suppléant n'en dispose que s'il les tient de l'article L. 2315-9, du protocole préélectoral, ou du remplacement momentané d'un titulaire (n° 20-21.269, n° 20-16.333) ; leur nombre s'apprécie, dans une entreprise divisée en établissements distincts, en fonction de l'effectif de l'établissement (n° 24-17.361). Le temps passé est de plein droit du temps de travail payé à l'échéance normale : l'employeur qui entend en contester l'usage doit payer d'abord et saisir le juge ensuite (n° 19-22.038).",
 "Trois décisions élargissent le cadre : la liberté de déplacement des élus et des représentants syndicaux, pendant et hors les heures de délégation (n° 22-22.145) ; l'articulation de l'affichage des informations du comité avec le respect de la vie personnelle du salarié, qui n'y fait pas par lui-même obstacle (n° 20-14.416) ; et l'inscription de droit à l'ordre du jour de la demande d'explications formée au titre du droit d'alerte économique (n° 22-10.586).",
],
F: [
 "La commission santé, sécurité et conditions de travail a produit une série courte mais cohérente. Ses membres sont désignés par le comité parmi ses membres, par résolution adoptée dans les conditions de l'article L. 2315-32, pour une durée qui prend fin avec le mandat des élus (n° 19-14.224) ; le comité ne peut pas les remplacer avant ce terme, hors les cas de fin anticipée de l'article L. 2314-33 (n° 24-22.914). Les dispositions de l'article L. 2315-39 sont d'ordre public : là où un troisième collège a été institué, un siège au moins doit lui être attribué (n° 24-12.295).",
 "Le contentieux de ces désignations suit celui des élections : tribunal judiciaire, délai de quinze jours de l'article R. 2314-24 (n° 23-20.714, n° 24-60.197). Une décision isolée mais utile complète la rubrique : dans une entreprise dotée d'un seul comité, le registre d'alerte en matière de risque grave pour la santé publique ou l'environnement est tenu au siège et n'a pas à être dupliqué dans chaque établissement (n° 21-16.993).",
],
G: [
 "Un seul arrêt publié sur les budgets dans tout le corpus, et il porte sur la transparence interne du comité : tous ses membres ont un égal accès à ses archives et à ses documents administratifs et comptables (n° 25-10.126). C'est peu, et il faut le dire : le contentieux du calcul de la masse salariale brute, de la subvention de fonctionnement et de la contribution aux activités sociales et culturelles n'a pas donné lieu, sur la période et parmi les décisions publiées, à un arrêt rattachable au régime du comité social et économique. Sur ces questions, il faut se reporter aux textes — articles L. 2315-61, L. 2312-81 et L. 2312-83 — et à la jurisprudence rendue sous l'empire du comité d'entreprise, qui n'entre pas dans le champ de ce recueil.",
],
H: [
 "L'expertise est le domaine où le calendrier décide de tout. L'employeur qui entend contester dispose d'un délai de dix jours (article R. 2315-49), mais le point de départ change selon l'objet de la contestation : délibération pour la nécessité, désignation pour le choix de l'expert, notification du cahier des charges pour le coût prévisionnel, notification du coût final pour celui-ci (n° 21-16.996). La Cour a assoupli ce point de départ au nom du procès équitable : le délai de contestation de la nécessité ne court qu'à compter du jour où l'employeur a été mis en mesure de connaître la délibération (n° 22-10.761), et le délai exprimé en jours ne commence à courir que le lendemain de l'acte (n° 22-21.892). Devant le tribunal judiciaire statuant selon la procédure accélérée au fond, la date de saisine est celle de l'assignation (n° 24-12.816).",
 "Sur l'étendue de la mission, la Cour est large. L'expert désigné pour la consultation sur la situation économique et financière peut porter ses investigations sur la situation du groupe (n° 21-23.393) ; celui désigné pour la consultation sur la politique sociale peut demander l'audition de salariés, avec l'accord de l'employeur (n° 22-10.293) ; le plan de mobilité entre dans le champ des informations à remettre (n° 23-22.733). L'expertise en vue de préparer la négociation sur l'égalité professionnelle est ouverte dans les entreprises d'au moins trois cents salariés (n° 19-23.589).",
 "Deux décisions de 2026 bornent le champ en matière de licenciement économique, et elles intéressent directement l'employeur : l'expertise de l'article L. 1233-34 est ouverte au comité en cas de projet portant sur au moins dix salariés dans une même période de trente jours (n° 23-22.270), mais aucune mesure d'expertise n'est prévue en deçà de ce seuil — la contestation par l'employeur d'une expertise décidée dans ce cas n'a donc pas d'objet légal (n° 25-13.280).",
],
I: [
 "Trois arrêts. Le comité d'établissement peut recourir à un expert lorsqu'il est lui-même compétent, ce qui suppose que la consultation soit conduite à son niveau (n° 20-19.974). Les contestations relatives au comité central relèvent du tribunal du siège de l'entreprise, parce que ses représentants exercent leur mandat au niveau de l'entreprise dans son ensemble (n° 22-21.239). Enfin, le mandat de délégué au comité central cesse à l'expiration de sa durée légale ou avec le mandat d'élu au comité d'établissement, et aucun texte n'ouvre de faculté de révocation (n° 24-14.344).",
],
J: [
 "Aucun arrêt du corpus ne se rattache au délit d'entrave. Ce n'est pas un oubli de classement : la recherche, limitée aux décisions publiées au Bulletin ou au Rapport et mentionnant le comité social et économique dans leur visa, leur sommaire ou leur titrage, n'en a ramené aucun sur la période. Le régime reste celui de l'article L. 2317-1 — un an d'emprisonnement et 7 500 euros d'amende pour l'entrave à la constitution du comité ou à la libre désignation de ses membres, 7 500 euros pour l'entrave à son fonctionnement régulier —, mais il faut le dire plutôt que de combler le vide par des décisions rendues sous l'empire du comité d'entreprise.",
],
K: [
 "Deux règles de seuil commandent la rubrique. Le délégué syndical n'est de droit représentant syndical au comité que dans les entreprises de moins de trois cents salariés et dans les établissements qui en relèvent ; au-delà, la désignation d'un représentant distinct est possible (n° 20-13.694, n° 23-18.331, n° 25-17.467). Et cette désignation est réservée aux organisations reconnues représentatives : le représentant de section syndicale n'y a pas droit (n° 20-20.397). Un même salarié ne peut siéger dans le même comité à la fois comme élu et comme représentant syndical, les fonctions délibératives et consultatives étant inconciliables (n° 18-23.764, n° 19-13.269).",
 "La désignation du délégué syndical a produit sa propre série autour du score personnel de dix pour cent. L'annulation de l'élection prononcée au titre de la représentation équilibrée est sans effet sur cette condition (n° 18-19.379). Le syndicat peut désigner un candidat présenté sur la liste d'un autre syndicat qui l'accepte (n° 19-14.605) ; lorsque tous les élus ou candidats qualifiés ont renoncé, il peut désigner un adhérent ou un ancien élu (n° 19-24.678), la renonciation devant être établie (n° 21-23.348). Le délégué supplémentaire suppose à la fois la représentativité et des élus dans au moins deux collèges, l'effectif de cinq cents salariés s'appréciant dans le périmètre de la désignation (n° 20-17.688).",
 "La rubrique porte enfin deux acquis de portée générale. Une organisation non signataire est recevable à contester un accord collectif au nom du droit au recours effectif (n° 20-18.442), dans le prolongement des arrêts du 2 mars 2022 sur l'exception d'illégalité. Et le représentant de proximité, protégé au titre de l'article L. 2411-1, 4°, a droit, lorsque sa prise d'acte produit les effets d'un licenciement nul, à l'indemnité pour violation du statut protecteur (n° 23-12.990) : la protection attachée à ce mandat conventionnel est celle du droit commun des salariés protégés.",
],
};
